services:
  ui:
    build: 
      context: ./gotocloud-appointment-app-ui
      dockerfile: DockerfileStage
    ports:
      - "80:80"
  doctors-api:
    image: yantraqa/gotocloud-doctor-api:latest
    ports:
      - "9000:9000"
