pipeline {
    agent any
    stages {
        stage('Build Create and Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'p', usernameVariable: 'u')]) {
                   sh "docker build --tag yantraqa/gotocloud-appointment-app-ui:latest ."
                }
            }
        }
    }
}