pipeline {
    agent any
    stages {
        stage('Unit Test and Sonar Analysis-mvn test') {
            steps {
                withEnv(['SONAR_TOKEN=0ab2cf1faf9fb442a7fa818f57cf552e1d3b9649']) {
                     sh ' mvn -f gotocloud-appointment-app-backend/gotocloud-doctor-api/pom.xml -B test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=akashdktyagi_gotocloud-appointments-app'
                }

            }
        }

        stage('Create and Push Image') {
            when {
                expression { params.StageToRun == "BUILD_IMAGE" }
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'p', usernameVariable: 'u')]) {
                   sh "mvn -f gotocloud-appointment-app-backend/gotocloud-doctor-api/pom.xml -B clean install -Djib.to.auth.username=$u -Djib.to.auth.password=$p"
                }

            }
        }

    }
}